### ISSUE TITLE
Warning message: In fun(libname, pkgname) : couldn't connect to display "localhost:10.0" while "sonar get_island"

### ISSUE THREAD

**Issue by Carpenter232** [scharch/zap#14]
Hi there! I am now following the vignette to run the example 'cap256-week34H'. However, it stops with the warning message above. You can see the whole message and the command below.

root@059beae7bb41:/cap256-week34H$ sonar get_island output/tables/cap256-week34H_goodVJ_unique_id-div.tab --mab CAP256-VRC26.01 --mab CAP256-VRC26.08
Loading required package: misc3d
Warning message:
In fun(libname, pkgname) : couldn't connect to display "localhost:10.0"
Error in .External2(C_X11, d$display, d$width, d$height, d$pointsize,  : 
  unable to start device X11
Calls: getIsland -> X11
In addition: Warning message:
In X11(type = "Xlib", family = "misc") :
  unable to open connection to X11 display ''

I tried some advice to fix the problem, but it did not work. I am running the example on a server through Xshell. The problem exists when SONAR is installed locally or by DOCKER. Hope you can help me, thank you!

**Comment by scharch** [comment]
The vignette script only checks to make sure that the `$DISPLAY` environmental variable is set (ie `[ -n "$DISPLAY" ]`), however if the assigned value is wrong, it will still produce this error. If you are having trouble determining the correct address, you could null `$DISPLAY` so that the vignette script switches to its backup mode. For "live" data, you can also try using `xvfb-run`.
